//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MC2_Sales_and_Inventory_System
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MC2Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MC2Entities object using the connection string found in the 'MC2Entities' section of the application configuration file.
        /// </summary>
        public MC2Entities() : base("name=MC2Entities", "MC2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MC2Entities object.
        /// </summary>
        public MC2Entities(string connectionString) : base(connectionString, "MC2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MC2Entities object.
        /// </summary>
        public MC2Entities(EntityConnection connection) : base(connection, "MC2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AdminTable> AdminTables
        {
            get
            {
                if ((_AdminTables == null))
                {
                    _AdminTables = base.CreateObjectSet<AdminTable>("AdminTables");
                }
                return _AdminTables;
            }
        }
        private ObjectSet<AdminTable> _AdminTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HistoryLogin> HistoryLogins
        {
            get
            {
                if ((_HistoryLogins == null))
                {
                    _HistoryLogins = base.CreateObjectSet<HistoryLogin>("HistoryLogins");
                }
                return _HistoryLogins;
            }
        }
        private ObjectSet<HistoryLogin> _HistoryLogins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LoginTable> LoginTables
        {
            get
            {
                if ((_LoginTables == null))
                {
                    _LoginTables = base.CreateObjectSet<LoginTable>("LoginTables");
                }
                return _LoginTables;
            }
        }
        private ObjectSet<LoginTable> _LoginTables;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AdminTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdminTables(AdminTable adminTable)
        {
            base.AddObject("AdminTables", adminTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HistoryLogins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHistoryLogins(HistoryLogin historyLogin)
        {
            base.AddObject("HistoryLogins", historyLogin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LoginTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLoginTables(LoginTable loginTable)
        {
            base.AddObject("LoginTables", loginTable);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MC2Model", Name="AdminTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AdminTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AdminTable object.
        /// </summary>
        /// <param name="indexNumber">Initial value of the IndexNumber property.</param>
        /// <param name="itemImage">Initial value of the ItemImage property.</param>
        /// <param name="itemName">Initial value of the ItemName property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static AdminTable CreateAdminTable(global::System.Int32 indexNumber, global::System.Byte[] itemImage, global::System.String itemName, global::System.String description, global::System.Int32 quantity, global::System.Double price)
        {
            AdminTable adminTable = new AdminTable();
            adminTable.IndexNumber = indexNumber;
            adminTable.ItemImage = itemImage;
            adminTable.ItemName = itemName;
            adminTable.Description = description;
            adminTable.Quantity = quantity;
            adminTable.Price = price;
            return adminTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IndexNumber
        {
            get
            {
                return _IndexNumber;
            }
            set
            {
                if (_IndexNumber != value)
                {
                    OnIndexNumberChanging(value);
                    ReportPropertyChanging("IndexNumber");
                    _IndexNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IndexNumber");
                    OnIndexNumberChanged();
                }
            }
        }
        private global::System.Int32 _IndexNumber;
        partial void OnIndexNumberChanging(global::System.Int32 value);
        partial void OnIndexNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] ItemImage
        {
            get
            {
                return StructuralObject.GetValidValue(_ItemImage);
            }
            set
            {
                if (!StructuralObject.BinaryEquals(_ItemImage, value))
                {
                    OnItemImageChanging(value);
                    ReportPropertyChanging("ItemImage");
                    _ItemImage = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ItemImage");
                    OnItemImageChanged();
                }
            }
        }
        private global::System.Byte[] _ItemImage;
        partial void OnItemImageChanging(global::System.Byte[] value);
        partial void OnItemImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ItemName
        {
            get
            {
                return _ItemName;
            }
            set
            {
                if (_ItemName != value)
                {
                    OnItemNameChanging(value);
                    ReportPropertyChanging("ItemName");
                    _ItemName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ItemName");
                    OnItemNameChanged();
                }
            }
        }
        private global::System.String _ItemName;
        partial void OnItemNameChanging(global::System.String value);
        partial void OnItemNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if (_Description != value)
                {
                    OnDescriptionChanging(value);
                    ReportPropertyChanging("Description");
                    _Description = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if (_Quantity != value)
                {
                    OnQuantityChanging(value);
                    ReportPropertyChanging("Quantity");
                    _Quantity = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Quantity");
                    OnQuantityChanged();
                }
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if (_Price != value)
                {
                    OnPriceChanging(value);
                    ReportPropertyChanging("Price");
                    _Price = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Price");
                    OnPriceChanged();
                }
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MC2Model", Name="HistoryLogin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HistoryLogin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HistoryLogin object.
        /// </summary>
        /// <param name="no">Initial value of the No property.</param>
        public static HistoryLogin CreateHistoryLogin(global::System.Int32 no)
        {
            HistoryLogin historyLogin = new HistoryLogin();
            historyLogin.No = no;
            return historyLogin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.Int32 _No;
        partial void OnNoChanging(global::System.Int32 value);
        partial void OnNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Time_LoggedIn
        {
            get
            {
                return _Time_LoggedIn;
            }
            set
            {
                OnTime_LoggedInChanging(value);
                ReportPropertyChanging("Time_LoggedIn");
                _Time_LoggedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time_LoggedIn");
                OnTime_LoggedInChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Time_LoggedIn;
        partial void OnTime_LoggedInChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTime_LoggedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Time_LoggedOut
        {
            get
            {
                return _Time_LoggedOut;
            }
            set
            {
                OnTime_LoggedOutChanging(value);
                ReportPropertyChanging("Time_LoggedOut");
                _Time_LoggedOut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time_LoggedOut");
                OnTime_LoggedOutChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Time_LoggedOut;
        partial void OnTime_LoggedOutChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTime_LoggedOutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SessionId
        {
            get
            {
                return _SessionId;
            }
            set
            {
                OnSessionIdChanging(value);
                ReportPropertyChanging("SessionId");
                _SessionId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SessionId");
                OnSessionIdChanged();
            }
        }
        private global::System.String _SessionId;
        partial void OnSessionIdChanging(global::System.String value);
        partial void OnSessionIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MC2Model", Name="LoginTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LoginTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LoginTable object.
        /// </summary>
        /// <param name="no">Initial value of the No property.</param>
        public static LoginTable CreateLoginTable(global::System.Int32 no)
        {
            LoginTable loginTable = new LoginTable();
            loginTable.No = no;
            return loginTable;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 No
        {
            get
            {
                return _No;
            }
            set
            {
                if (_No != value)
                {
                    OnNoChanging(value);
                    ReportPropertyChanging("No");
                    _No = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("No");
                    OnNoChanged();
                }
            }
        }
        private global::System.Int32 _No;
        partial void OnNoChanging(global::System.Int32 value);
        partial void OnNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Answer
        {
            get
            {
                return _Answer;
            }
            set
            {
                OnAnswerChanging(value);
                ReportPropertyChanging("Answer");
                _Answer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Answer");
                OnAnswerChanged();
            }
        }
        private global::System.String _Answer;
        partial void OnAnswerChanging(global::System.String value);
        partial void OnAnswerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Registered
        {
            get
            {
                return _Date_Registered;
            }
            set
            {
                OnDate_RegisteredChanging(value);
                ReportPropertyChanging("Date_Registered");
                _Date_Registered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Registered");
                OnDate_RegisteredChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Registered;
        partial void OnDate_RegisteredChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_RegisteredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Time_Registered
        {
            get
            {
                return _Time_Registered;
            }
            set
            {
                OnTime_RegisteredChanging(value);
                ReportPropertyChanging("Time_Registered");
                _Time_Registered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time_Registered");
                OnTime_RegisteredChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Time_Registered;
        partial void OnTime_RegisteredChanging(Nullable<global::System.TimeSpan> value);
        partial void OnTime_RegisteredChanged();

        #endregion

    
    }

    #endregion

    
}
